### ISSUE TITLE
Error handling for worker tests

### ISSUE THREAD

**Issue by dlsteuer** [battlesnakeio/engine#8]
The `TestWorker_Run` method is currently skipped because it checks explicitly for a `DeadlineExceeded` error, but it's possible it could receive an GRPC wrapped timeout error as well.

**Comment by ColDog** [comment]
@dlsteuer where is it commented?

**Comment by dlsteuer** [comment]
https://github.com/battlesnakeio/engine/blob/4939fa4ad6f07e6507b73fc04e354bbe661a29cf/worker/worker_test.go#L45

**Comment by ColDog** [comment]
Ah this won't work likely, the rule package doesn't respect context .

**Comment by dlsteuer** [comment]
Not sure what you mean, but the game tick loop in worker.go does at the top of the loop

https://github.com/battlesnakeio/engine/blob/master/worker/worker.go#L32-L36

**Comment by ColDog** [comment]
Basically this line here:

https://github.com/battlesnakeio/engine/blob/master/worker/worker.go#L40

Context cancellation isn't respected inside those functions.

**Comment by ColDog** [comment]
I think this is all sorted now, the structure has changed significantly. Going to close this off.
